// src/content_script/components/Footer.vue
<template lang="pug">
footer.footer
  .content.has-text-centered
    p
      b-tag(type="is-info")
        | SYNCROOM Plus Version {{ version }}

    p
      | {{ translate("developed_by") }}
      a(href='https://twitter.com/koedamedev', target="_blank", rel="noopener noreferrer")
        strong
          | 肥溜め
        | @koedamedev
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api';
import { translate } from '../../lib/i18n';
import { browser } from 'webextension-polyfill-ts';

export default defineComponent({
  setup() {
    return {
      version: browser.runtime.getManifest().version,
      translate,
    };
  },
});
</script>

// src/components/Parts/Footer.tsx
import React from 'react';

import { useTranslation } from '../../lib/i18n';

interface Props {
  version: string;
}

const Component: React.FC<Props> = ({ version }: Props) => {
  const { t } = useTranslation();

  return (
    <footer className="bg-gray-800">
      <div className="max-w-7xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
        <div className="flex justify-center">
          <p className="bg-gray-600 text-white rounded py-1 px-2">SYNCROOM Plus Version {version}</p>
        </div>
        <p className="mt-8 text-center text-base text-gray-400">
          {t('developed_by')}
          <a className="hover:text-gray-200" href="https://twitter.com/koedamedev" target="_blank" rel="noopener noreferrer">
            <strong>肥溜め</strong>@koedamedev
          </a>
        </p>
      </div>
    </footer>
  );
};

export default React.memo(Component);
